import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CounterProvider from "@/context/CounterContext";
import Global from "@/components/global/Global";
import ResourceFormSelector from "@/components/newResources/ResourceFormSelector";
import PathNavigator from "@/components/fileContent/PathNavigator";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="bottom-right" />
        <div className="flex flex-col h-screen">
          <CounterProvider>
            <Global />
            <ResourceFormSelector />
            <div className=" min-h-24 bg-zinc-800 pt-4 space-y-4 flex-1">
              <PathNavigator />
              {children}
            </div>
          </CounterProvider>
        </div>
      </body>
    </html>
  );
}
